과제/Django/assign_pjt/assign_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('post/', include('post.urls')),
]

과제/Django/assign_pjt/post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name = 'index'),
    path('detail/<int:pk>/', views.detail, name = 'detail'),
    path('create/',views.create, name = 'create'),
    path("<int:pk>/edit", views.edit, name="edit"),
    path("<int:pk>/update", views.update, name = "update"),
    path('<int:pk>/del_post', views.del_post, name = 'del_post'),


]

과제/Django/assign_pjt/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [    
    path('login/', views.login, name = 'login'),
    path("logout/", views.logout, name='logout'),    
    path('signup/', views.signup, name = 'signup'),
    path("delete/", views.delete, name='delete'),
    path('profile/', views.profile, name = 'profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('update/', views.update, name="update"),
    path("passward/", views.change_passward, name = "change_passward"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

과제/Django/assign_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width={device-width}, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="navbar">
        {% if request.user.is_authenticated %}
            <h3>안녕하세요, {{ user }}님</h3>
            <form action="{% url 'users:logout' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="로그아웃">
            </form><br><br>
            <a href="{% url "users:update" %}">회원정보수정</a><br><br>
            <a href="{% url "users:profile" %}">프로필</a>
            <form action="{% url 'users:delete' %}"method="POST">
                {% csrf_token %}
                <input type="submit" value="회원탈퇴"></input>
            </form>
        {% else %}
            <a href="{% url 'users:login'%}">로그인</a>
            <a href="{% url 'users:signup'%}">회원가입</a>
        {% endif %}
    </div>
    
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    
</body>
</html>