과제/Django/assign_pjt/assign_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('post/', include('post.urls')),
]

과제/Django/assign_pjt/post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name = 'index'),
    path('detail/<int:pk>/', views.detail, name = 'detail'),
    path('create/',views.create, name = 'create'),
    path("<int:pk>/edit", views.edit, name="edit"),
    path("<int:pk>/update", views.update, name = "update"),
    path('<int:pk>/del_post', views.del_post, name = 'del_post'),


]

과제/Django/assign_pjt/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [    
    path('login/', views.login, name = 'login'),
    path("logout/", views.logout, name='logout'),    
    path('signup/', views.signup, name = 'signup'),
    path("delete/", views.delete, name='delete'),
    path('profile/', views.profile, name = 'profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('update/', views.update, name="update"),
    path("passward/", views.change_passward, name = "change_passward"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

과제/Django/assign_pjt/post/models.py
from django.db import models
from django.conf import settings

class Posts(models.Model):
    title = models.CharField(max_length = 200)
    content = models.TextField()
    
    create_date = models.DateTimeField(auto_now_add=True)
    edited_date = models.DateTimeField(auto_now = True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="Post")
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content
  

과제/Django/assign_pjt/post/forms.py
from django import forms
from post.models import Posts

class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = "__all__"
        exclude = ('author',)

과제/Django/assign_pjt/post/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Posts
from .forms import PostForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):    
    post = Posts.objects.all().order_by("-id") 
    context = {
        "post" : post
    } 
    return render(request, "index.html", context)

@login_required
def create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit = False)
            post.author = request.user
            post.save()
            return redirect("post:detail",post.id)
    else : 
        form = PostForm()

    context = {"form":form}
    return render(request, "create.html", context)

def detail(request, pk):
    try :
        post = Posts.objects.get(pk=pk)
    except Posts.DoesNotExist:
        return redirect("post:index")

    context = {
        "post" : post,
    }
    return render(request, "detail.html",context)

def del_post(request,pk):
    post = Posts.objects.get(pk=pk)
    if request.method == "POST":
        post.delete()
        return redirect("post:index")
    return redirect("post:detail",post.pk)

def edit(request,pk):
    post = Posts.objects.get(pk=pk)
    context = {
        "post" : post,
    }
    return render(request,'edit.html', context)

def update(request,pk):
    post = Posts.objects.get(pk=pk)
    post.title = request.POST.get("title")
    post.content = request.POST.get("content")
    post.save()
    return redirect("post:detail", post.pk)

과제/Django/assign_pjt/post/templates/create.html
{% extends "base.html" %}

{% block content %}

<h1>Create New Post</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">저장</button>
</form>
{% endblock content %}

과제/Django/assign_pjt/post/templates/detail.html
{% extends "base.html" %}

{% block content %}

    <h2>글 상세 페이지</h2>
   
    <p>ID    : {{post.id}} </p>
    <p>제목   : {{post.title}}</p>
    <p>내용   : {{post.content}}</p>   
    <p>작성자 : {{post.author}} </p>     
    <p>작성일 : {{post.create_date}}</p>
    <p>수정일 : {{post.edited_date}}</p>
    

    <a href="{% url 'post:index' %}">목록 보기</a>

    <hr>
    <a href="{% url 'post:edit' post.pk %}"><button>글수정</button></a><br><br>

    <form action="{% url 'post:del_post' post.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="글삭제">
    </form>

{% endblock content %}

과제/Django/assign_pjt/post/templates/edit.html
{% extends "base.html" %}


{% block content %}
<h1>Update Post</h1>

<form action="{% url 'post:update' pk=post.pk %}" method="POST">
	  {% csrf_token %}
    <label for="title">제목</label>
    <input type="text" name="title" id="title" value={{post.title}}><br><br>

    <label for="content">내용</label>
    <textarea name="content" id="content" cols="30" rows="10">{{post.content}}</textarea><br><br>

    <button type="submit">저장</button>
</form>


{% endblock content %}

과제/Django/assign_pjt/post/templates/index.html
{% extends 'base.html' %}


{% block content %}
	<h1> INDEX</h1>
    {% if request.user.is_authenticated %}
        <a href="{% url 'post:create' %}">새 글 작성</a>
    {% else %}
        <a href="{% url 'users:login' %}">로그인하고 글 작성하기</a>
    {% endif %}

    
    
    
    <ul>
        {% for posting in post %}
            <li>
                <a href = "{% url 'post:detail' posting.id %}">
                    <div>[{{posting.id}}] {{posting.title}}</div>
                </a>
                <br>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

과제/Django/assign_pjt/post/templates/new.html
{% extends 'base.html' %}

{% block content %}
    <h1>게시글 작성</h1>
    <form action="{% url 'post:create' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
    
        <button type="submit">저장</button>
    </form>

{% endblock content %}