과제/Django/assign_pjt/assign_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('post/', include('post.urls')),
]

과제/Django/assign_pjt/post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.index, name = 'index'),
    path('detail/<int:pk>/', views.detail, name = 'detail'),
    path('create/',views.create, name = 'create'),
    path("<int:pk>/edit", views.edit, name="edit"),
    path("<int:pk>/update", views.update, name = "update"),
    path('<int:pk>/del_post', views.del_post, name = 'del_post'),


]

과제/Django/assign_pjt/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [    
    path('login/', views.login, name = 'login'),
    path("logout/", views.logout, name='logout'),    
    path('signup/', views.signup, name = 'signup'),
    path("delete/", views.delete, name='delete'),
    path('profile/', views.profile, name = 'profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('update/', views.update, name="update"),
    path("passward/", views.change_passward, name = "change_passward"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

과제/Django/assign_pjt/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    profile_image = models.ImageField(upload_to='profile_images/', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    




# class Posts(models.Model):
#     title = models.CharField(max_length = 200)
#     content = models.TextField()
    
#     create_date = models.DateTimeField(auto_now_add=True)
#     edited_date = models.DateTimeField(auto_now = True)
#     author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="Post")
#     def __str__(self):
#         return self.title

과제/Django/assign_pjt/users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.urls import reverse
from .models import User  

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username',
                  "email",
                "first_name",
                "last_name",]
        
class AssingForm(forms.Form):
    title = forms.CharField(max_length=20)
    content = forms.CharField()

class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
        )
    
    def __init__(self, *args, **kwargs): #링크를 패스워드 변경으로 오버라이딩. 
        super().__init__(*args, **kwargs)
        if self.fields.get("password"):
            password_help_text = (
                "You can change the password " '<a href="{}">here</a>.'
            ).format(reverse('users:change_passward'))
            self.fields["password"].help_text = password_help_text




class ProfileUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['first_name', 
                  'last_name', 
                  'email', 
                  'profile_image', 
                  'bio']

과제/Django/assign_pjt/users/views.py
# accounts/views.py

from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.http import require_GET, require_POST
from django.views.decorators.http import require_http_methods
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib import messages
from .forms import ProfileUpdateForm



def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("post:index")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "login.html", context)

@login_required
def logout(request):
    if request.method == "POST":
        auth_logout(request)
    return redirect("post:index")

def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("post:index")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "signup.html", context)

@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect("post:index")

@require_http_methods(["GET","POST"])
def update(request):
    
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect("post:index")
    else : 
        form = CustomUserChangeForm(instance=request.user)
    context = {"form" : form}
    return render(request, 'update.html', context)

def change_passward(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("post:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "change_passward.html", context)

@login_required
def profile(request):    
    context = {'user': request.user}
    return render(request, 'profile.html', context)

@login_required
def update_profile(request):
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()            
            return redirect('users:profile')  # 프로필 페이지로 리디렉션
    else:
        form = ProfileUpdateForm(instance=request.user)
    context = {
        'form': form
        }
    return render(request, 'update_profile.html', )

과제/Django/assign_pjt/users/templates/change_passward.html
{% extends "base.html" %}

{% block content %}
<h1>비밀번호 변경</h1>

<form action="{% url 'users:change_passward' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">비밀번호 변경</button>
</form>
{% endblock content %}

과제/Django/assign_pjt/users/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>로그인</h1>

    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">로그인</button>
    </form>

{% endblock content %}

과제/Django/assign_pjt/users/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
		<h1> {{ user }}의 프로필 페이지 </h1>

		{% if user.profile_image %}
        <img src="{{ user.profile_image.url }}" alt="Profile picture of {{ user.username }}">
    {% else %}
        <p>프로필 사진이 없습니다.</p>
    {% endif %}

    <div>
		{% csrf_token %}
        {{ form.as_p }}
		
    </div>
	<a href="{% url 'users:update_profile' %}">프로필 수정</a>
		<a href="{% url 'post:index'%}">홈으로 돌아가기</a>
		
{% endblock content %}

과제/Django/assign_pjt/users/templates/signup.html
{% extends "base.html" %}

{% block content %}
    <h1>회원가입</h1>
    <form action="{% url "users:signup" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">회원가입</button>
    </form>
{% endblock %}

과제/Django/assign_pjt/users/templates/update.html
{% extends "base.html" %}

{% block content %}
    <h1>회원정보수정</h1>
    
    <form action="{% url 'users:update' %}" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">수정하기</button>
    </form>

{% endblock %}

과제/Django/assign_pjt/users/templates/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h1>프로필 수정</h1>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장</button>
    </form>

    <a href="{% url 'users:profile' %}" class="btn btn-secondary">프로필로 돌아가기</a>
{% endblock content %}